= Various Lazybones templates

== Installation of Lazybones using gvm (Linux, OS/X)

Install gvm:

-----------
$ curl -s get.gvmtool.net | bash
-----------

Install lazybones:

-----------
$ gvm install lazybones
-----------

Add the entry +"svene/lazybones"+ to your +$HOME/.lazybones/config.groovy+ file:

-----------
bintrayRepositories = [
    "svene/lazybones",
    ...
-----------


== Installation of Lazybones without gvm
Grab the distribution from https://bintray.com/pkg/show/general/pledbrook/lazybones-templates/lazybones[Bintray], unpack it to a local directory, and then add its +bin+ directory to your PATH environment variable.

== Usage

=== JavaEE 7 Template
In an arbitrary directory execute +lazybones create javaee-seven myjavaee7project+ which will create the folder +myjavaee7project+ and expand the template into it.
The folder contains a +build.gradle+ file for the gradle folks and a +pom.xml+ for those who prefer maven. BTW: all the credit goes to Adam Bien of course: https://github.com/AdamBien/javaee7-essentials-archetype

== Development

* Make a change in a template, e.g. +templates/javaee-seven+
* In top folder execute +./gradlew installTemplateJavaeeSeven+ which will install the +javaee-seven+ template into +~/.lazybones/templates/javaee-seven-0.0.1.zip+
* In an arbitrary directory execute +lazybones create javaee-seven 0.0.1 javaee7+ which will create the folder +javaee7+ and expand the template into it.
* Repeat the previous steps until you are satisfied with the result

== Publishing
* In the top level folder invoke +./gradlew publishTemplateJavaeeSeven+ . Note: the first time a package needs to be created with the bintray Web-GUI (in my case in the 'lazybones' repository) with a name ending in '-template' (for this example 'javaee-seven-template').
